/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author evandex
 */
public class DelayPanel extends javax.swing.JPanel {
    // Do I really have to do it like this?
    SpinnerNumberModel numberModel1 = new javax.swing.SpinnerNumberModel(1000, 500, 100000, 500);
    SpinnerNumberModel numberModel2 = new javax.swing.SpinnerNumberModel(1000, 500, 100000, 500);
    SpinnerNumberModel numberModel3 = new javax.swing.SpinnerNumberModel(1000, 500, 100000, 500);

    /**
     * Creates new form DelayPanel
     */
    public DelayPanel(String label) {
        initComponents();
        trafficLabel.setText("Set delays for traffic light " + label);
        redSpinner.setToolTipText("Red light duration in milliseconds");
        yellowSpinner.setToolTipText("Yellow light duration in milliseconds");
        greenSpinner.setToolTipText("Green light duration in milliseconds");
        redSpinner.setFocusable(true);
        yellowSpinner.setFocusable(true);
        greenSpinner.setFocusable(true);
        setPreferredSize(new Dimension(300, 100));
    }
    
    public int getRedDelay() {
        return (int) redSpinner.getValue();
    }
    
    public int getYellowDelay() {
        return (int) yellowSpinner.getValue();
    }
    
    public int getGreenDelay() {
        return (int) greenSpinner.getValue();
    }
    
    public String getLabel() {
        return trafficLabel.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stuffPanel = new javax.swing.JPanel();
        labelPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spinnerPanel = new javax.swing.JPanel();
        redSpinner = new javax.swing.JSpinner(numberModel1);
        yellowSpinner = new javax.swing.JSpinner(numberModel2);
        greenSpinner = new javax.swing.JSpinner(numberModel3);
        topPanel = new javax.swing.JPanel();
        trafficLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(300, 90));
        setLayout(new java.awt.BorderLayout());

        stuffPanel.setLayout(new java.awt.GridLayout(2, 1));

        labelPanel.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel1.setText("Red Light");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 25));
        labelPanel.add(jLabel1);

        jLabel3.setText("Yellow Light");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 25));
        labelPanel.add(jLabel3);

        jLabel4.setText("Green Light");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 25));
        labelPanel.add(jLabel4);

        stuffPanel.add(labelPanel);

        redSpinner.setPreferredSize(new java.awt.Dimension(80, 22));
        spinnerPanel.add(redSpinner);

        yellowSpinner.setPreferredSize(new java.awt.Dimension(80, 22));
        spinnerPanel.add(yellowSpinner);

        greenSpinner.setMinimumSize(new java.awt.Dimension(80, 22));
        greenSpinner.setPreferredSize(new java.awt.Dimension(80, 22));
        spinnerPanel.add(greenSpinner);

        stuffPanel.add(spinnerPanel);

        add(stuffPanel, java.awt.BorderLayout.CENTER);

        topPanel.setPreferredSize(new java.awt.Dimension(300, 30));
        topPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        trafficLabel.setText("Set Delay for Traffic Light A");
        topPanel.add(trafficLabel);

        add(topPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner greenSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JSpinner redSpinner;
    private javax.swing.JPanel spinnerPanel;
    private javax.swing.JPanel stuffPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel trafficLabel;
    private javax.swing.JSpinner yellowSpinner;
    // End of variables declaration//GEN-END:variables
}
