package UI;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author evandex
 */
public class TrafficFrame extends JFrame {
    private final TrafficPanel canvas;
    /**
     * Creates new form TrafficFrame
     */
    public TrafficFrame() {
        initComponents();
        System.out.println("TrafficContainerPanel size: " + trafficContainerPanel.getWidth() + " " + trafficContainerPanel.getHeight());
        System.out.println("Frame size: " + getSize());
        canvas = new TrafficPanel(trafficContainerPanel.getWidth(), trafficContainerPanel.getHeight(), trafficContainerPanel.getBackground());
        System.out.println("canvas size: " + canvas.getSize());
        trafficContainerPanel.add(canvas);
        trafficContainerPanel.setVisible(true);
        setPreferredSize(new Dimension(800, 600));
        setLocationRelativeTo(null);
        SwingUtilities.invokeLater(() -> {
        canvas.repositionNodes();
        canvas.repaint();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serialSenderPanel = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();
        arrowCheckBox = new javax.swing.JCheckBox();
        labelCheckBox = new javax.swing.JCheckBox();
        filePanel = new javax.swing.JPanel();
        trafficContainerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serialSenderPanel.setBackground(new java.awt.Color(100, 100, 100));
        serialSenderPanel.setPreferredSize(new java.awt.Dimension(60, 250));
        serialSenderPanel.setLayout(new javax.swing.BoxLayout(serialSenderPanel, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(serialSenderPanel, java.awt.BorderLayout.LINE_START);

        settingsPanel.setBackground(new java.awt.Color(100, 100, 100));
        settingsPanel.setLayout(new javax.swing.BoxLayout(settingsPanel, javax.swing.BoxLayout.PAGE_AXIS));

        arrowCheckBox.setText("Hide Arrows");
        arrowCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowCheckBoxActionPerformed(evt);
            }
        });
        settingsPanel.add(arrowCheckBox);

        labelCheckBox.setText("Hide Labels");
        labelCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelCheckBoxActionPerformed(evt);
            }
        });
        settingsPanel.add(labelCheckBox);

        getContentPane().add(settingsPanel, java.awt.BorderLayout.LINE_END);

        filePanel.setBackground(new java.awt.Color(50, 50, 50));
        filePanel.setPreferredSize(new java.awt.Dimension(400, 50));
        getContentPane().add(filePanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout trafficContainerPanelLayout = new javax.swing.GroupLayout(trafficContainerPanel);
        trafficContainerPanel.setLayout(trafficContainerPanelLayout);
        trafficContainerPanelLayout.setHorizontalGroup(
            trafficContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        trafficContainerPanelLayout.setVerticalGroup(
            trafficContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        getContentPane().add(trafficContainerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arrowCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowCheckBoxActionPerformed
        if (arrowCheckBox.isSelected()) canvas.setShowArrows(false);
        else canvas.setShowArrows(true);
    }//GEN-LAST:event_arrowCheckBoxActionPerformed

    private void labelCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelCheckBoxActionPerformed
        if (labelCheckBox.isSelected()) canvas.setShowLabels(false);
        else canvas.setShowLabels(true);
    }//GEN-LAST:event_labelCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrafficFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrafficFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrafficFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrafficFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrafficFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox arrowCheckBox;
    private javax.swing.JPanel filePanel;
    private javax.swing.JCheckBox labelCheckBox;
    private javax.swing.JPanel serialSenderPanel;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JPanel trafficContainerPanel;
    // End of variables declaration//GEN-END:variables
}
